services:
  app:
    build: .
    container_name: tf-app-v2
    ports:
      - "8086:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://tf-db-v2:3306/projectdb?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Qwe.123*
    depends_on:
      db:
        condition: service_healthy
    networks:
      - tf-net-final

  db:
    image: mysql:8.0
    container_name: tf-db-v2
    environment:
      MYSQL_ROOT_PASSWORD: Qwe.123*
      MYSQL_DATABASE: projectdb
    ports:
      - "3310:3306"
    volumes:
      - tf-vol-final:/var/lib/mysql
    networks:
      - tf-net-final
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pQwe.123*" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  tf-vol-final:


networks:
  tf-net-final:
